"""added sequence in question type

Revision ID: 4ed520a31e6e
Revises: dddabef3a4e5
Create Date: 2021-08-12 12:39:20.103511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed520a31e6e'
down_revision = 'dddabef3a4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_type', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_type', 'sequence')
    # ### end Alembic commands ###
