"""added gender for employee

Revision ID: b05a6f03bd31
Revises: e746d691c696
Create Date: 2021-08-05 15:10:40.058652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05a6f03bd31'
down_revision = 'e746d691c696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('gender', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    # ### end Alembic commands ###
