"""empty message

Revision ID: b22d1271bcbc
Revises: 4ed520a31e6e
Create Date: 2021-08-16 09:41:02.670001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22d1271bcbc'
down_revision = '4ed520a31e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('response', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'response', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.drop_column('response', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
