"""added question description on question_response

Revision ID: dddabef3a4e5
Revises: e7d426b9433b
Create Date: 2021-08-11 15:46:45.131035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddabef3a4e5'
down_revision = 'e7d426b9433b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_response', sa.Column('question', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_response', 'question')
    # ### end Alembic commands ###
