"""added feedback on QuestionResponse

Revision ID: e746d691c696
Revises: a9717c3bef55
Create Date: 2021-08-04 17:02:51.402946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e746d691c696'
down_revision = 'a9717c3bef55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_response', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_response', 'feedback')
    # ### end Alembic commands ###
